### ISSUE TITLE
Return time in a ms from unix epoch format

### ISSUE THREAD

**Issue by jjcm** [jjcm/soci-backend#10]
How easy would it be to do that? Turns out it's a bit easier for me to do some computations with it. I.e. 

`1575504459492`

instead of 

`2019-12-05 11:45am`

**Comment by lapubell** [comment]
which endpoint are we adjusting on this issue? I just checked the "seconds remaining" header, and that is in int format.

**Comment by lapubell** [comment]
I just updated the /posts route with this, and pushed up a new build. If it was supposed to go somewhere else please call it out. Otherwise feel free to close this.

Thanks!

**Comment by jjcm** [comment]
yay
