### ISSUE TITLE
/comments/create endpoint

### ISSUE THREAD

**Issue by jjcm** [jjcm/soci-backend#16]
_POST_ call
_Private api endpoint_

Allows the creation of a comment. Example payload: 
```
{
  "post": "this_is_crazy", 
  "content": "I really like this",
  "user": "bojackson",
  "parent": /* some id for another comment, or null */,
}

```

**Comment by lapubell** [comment]
should we omit the "user" from the payload and assume that the person POSTing is the comment author? we can get that user from the JWT that should be with the payload.

how would you like this response to look? We could just have it be true (response code 201) or false (response code 500, 401, etc)

cool?

**Comment by jjcm** [comment]
> should we omit the "user" from the payload and assume that the person POSTing is the comment author? we can get that user from the JWT that should be with the payload.

Yea that's probably smart. No need for the user in the payload.

"how would you like this response to look? We could just have it be true (response code 201) or false (response code 500, 401, etc)"

Can we make the response be the full JSON representation of the comment? That way I can create the view representation of the comment on the frontend as soon as the response comes back. I.E.

```
{
      "id": "YPGpbT",
      "date": "1579838273544",
      "post": "this_is_crazy", 
      "content": "I really like this",
      "user": "bojackson",
      "upvotes": 0,
      "downvotes": 0,
}
```

**Comment by lapubell** [comment]
this is coming along, but I've spotted an inconsistency. In your examples here in this thread, you only ever have "content" defined, but in the docs it looks like the comments have a concept of a "type". I can see that when the "type" is set to text, then the comment body is stored in a "text" field. If the type is an image, then text is empty and "content" is set to the image URL.

I've got it working this way currently, but for now all I'm really doing is storing the text. We'll need to change the incoming request payload to have all those fields if we want this distinction in the future. I'll push up a build and update the docs when the next release goes out.

cheers!

**Comment by jjcm** [comment]
Ya in general, I'll ensure the spec here is up to date. Originally I was thinking I'd have content be like an attached image url or something, but because I'm changing how images work having a url for the image isn't needed in the post. 

Use the spec here, and lets update the migration to remove the "text" field.
