### ISSUE TITLE
A script that clones the latest of each repo and runs them with default settings.

### ISSUE THREAD

**Issue by jjcm** [jjcm/soci-backend#37]
This can be an entirely separate repo or a folder inside of soci-backend. If you think it should be a separate repo, then lemme know and I'll make the base repo to contribute to. 

What I'm looking for is a rich UI in a terminal that runs all of the microservices at once. It should be an easy way to get up and running for development. 

I'd highly recommend using a terminal UI library for this. This repo looks good: https://github.com/gizak/termui

Eventually we'll build in the frontend server as a part of this as well, but for now it should just be the backend microservices.

**Comment by lapubell** [comment]
This looks insanely fun to build. Does Sept work for you for us to get this going?
