### ISSUE TITLE
On each upvote, update the user's donations for that month.

### ISSUE THREAD

**Issue by jjcm** [jjcm/soci-backend#42]
Every time a user upvotes a posttag, we should update their donations for that month. 

## Example:

- Bob has a subscription of $5 per month
- We always take $1 per month for the server fee, so he has a donation pool of $4.
- Bob votes on Mary's post. The state of the donations is the following:
_Mary: $4_
- Bob votes on Sam's post. The state of the donations is the following:
_Mary: $2
Sam: $2_
- Bob votes on a different tag on the same post from Sam. We only change the donation table on the first vote on a post. The state of the donations is the following:
_Mary: $2
Sam: $2_

## Steps:

- [ ] Create a route for getting a user's donations for the month. Should return an array of {username, amount}. 
- [ ] Create a route for getting all of the posts that a user has voted on that month. Should return an array of unique Posts. If a user has voted on a post twice, it should not appear twice.

**Comment by lapubell** [comment]
need route `/user/up-voted-posts` - show all the posts the upvoted

need route `/user/donation?month=YYYY-MM` - something like this, make sure it matches other route params

the user is determined by the JWT content
