### ISSUE TITLE
Make signup require a username

### ISSUE THREAD

**Issue by jjcm** [jjcm/soci-backend#9]
Would be good to get a username in there. Once it's in, can we change the response for /posts to have the username in the `user` field instead of the email?

**Comment by lapubell** [comment]
Totes!

Should we make it optional? I'm guessing that if people sign up via social networks we won't be able to populate the username field with something by default. So, if they have a username we can show that, and if not it will fall back to email address. Thoughts?

**Comment by jjcm** [comment]
Keeping open for future completion of social authentication flow
